from pathlib import Path

from tools.annotation_converter.reader.base import BaseReader
import xmltodict

class XMLReader(BaseReader):
    """
    A reader class designed to parse Pascal VOC XML annotation files into Python dictionaries.

    This class uses the 'xmltodict' library to handle XML data efficiently. It is
    specifically optimized and tested for stability with XML files generated by
    the 'labelImg' annotation tool.
    """
    def read(self, file_path: Path) -> dict:
        """
        Reads the content of an XML file and converts it into a structured dictionary.

        Args:
            file_path (Path): The path to the source XML file.

        Returns:
            dict: A Python dictionary containing the parsed XML data.

        Raises:
            FileNotFoundError: If the XML file is not found at the given path.
            xmltodict.ParsingInterrupted: If the XML content is not valid or corrupted.
        """
        data = xmltodict.parse(file_path.read_text())
        return data