from dataclasses import dataclass

@dataclass
class Arguments:
    """Command arguments"""
    src: str = "src"
    dst: str = "--dst"
    pattern: str = "--pattern"
    p: str = "-p"
    repeat: str = "--repeat"
    r: str = "-r"
    sleep: str = "--sleep"
    s: str = "-s"
    step_sec: str = "--step_sec"
    step: str = "-step"
    type: str = "--type"
    t: str = "-t"
    remove: str = "--remove"
    rm: str = "-rm"
    log_level: str = "--log_level"
    log_path: str = "--log_path"
    datatype: str = "--datatype"
    method: str = "--method"
    m: str = "-m"
    action: str = "--action"
    a: str = "-a"
    threshold: str = "--threshold"
    core_size: str = "--core_size"
    n_jobs: str = "--n_jobs"
    cache_name: str = "--cache_name"
    a_suffix: str = "--a_suffix"
    a_source: str = "--a_source"
    destination_type: str = "--destination-type"
    img_path: str = "--img_path"
    extensions: str = "--ext"
    margin: str = "--margin"
    report_path: str = "--report_path"
