from dataclasses import dataclass


@dataclass
class ImageStatsKeys:
    """Constants for stats dictionary keys and default values."""
    path: str = "path"
    im_path: str = "im_path"
    mtime: str = "mtime"
    class_name: str = "class_name"
    objects_count: str = "objects_count"
    im_width: str = "im_width"
    im_height: str = "im_height"
    im_depth: str = "im_depth"
    im_brightness: str = "im_brightness"
    im_contrast: str = "im_contrast"
    im_blur_score: str = "im_blur_score"
    has_neighbors: str = "has_neighbors"
    object_width: str = "object_width"
    object_height: str = "object_height"
    object_aspect_ratio: str = "object_aspect_ratio"
    object_area: str = "object_area"
    object_relative_area: str = "object_relative_area"
    object_in_center: str = "object_in_center"
    object_in_right_side: str = "object_in_right_side"
    object_in_left_side: str = "object_in_left_side"
    object_in_top_side: str = "object_in_top_side"
    object_in_bottom_side: str = "object_in_bottom_side"
    object_in_left_top: str = "object_in_left_top"
    object_in_right_top: str = "object_in_right_top"
    object_in_left_bottom: str = "object_in_left_bottom"
    object_in_right_bottom: str = "object_in_right_bottom"
    full_size: str = "full_size"
    truncated_left: str = "truncated_left"
    truncated_right: str = "truncated_right"
    truncated_top: str = "truncated_top"
    truncated_bottom: str = "truncated_bottom"
    outlier_any: str = "outlier_any"
